config/routes.rb
Rails.application.routes.draw do
  resources :bookings

  devise_for :users

  resources :flights

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, class_name: "Flight", foreign_key: :arrival_airport_id
  has_many :departing_flights, class_name: "Flight", foreign_key: :departure_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport'
  belongs_to :departure_airport, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new(flight_id: params[:flight_id])
    @number_of_passengers = params[:number_of_tickets].to_i
    @number_of_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).confirmation_email.deliver_later
      end
      redirect_to @booking, notice: "Booking was successfully created."
    else
      render :new, status: :unprocessabel_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:number_of_passengers, :flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @arrival_options = Flight.pluck(:arrival_airport_id).map do |arrival|
      [ Airport.find_by(id: arrival).code, arrival ].uniq
    end.uniq

    @departure_options = Flight.pluck(:departure_airport_id).map do |departure|
      [ Airport.find_by(id: departure).code, departure ]
    end.uniq

    @avaialbe_flight_times = Flight.pluck(:start).map do |time|
      time.in_time_zone(Time.zone)
    end.uniq.sort

    @formatted_flight_times = @avaialbe_flight_times.map do |time|
      [time.strftime("%A, %B %d, %Y at %I:%M %p %Z"), time]
    end

    arrival_airport_id = params[:arrival_airport_id]
    departure_airport_id = params[:departure_airport_id]
    start = params[:start]
    passengers = params[:passengers]
    @number_of_tickets = params[:passengers]

    # all flights
    @flights = Flight.all

    # flights that match arrival
    @flights_arr = @flights.where(arrival_airport_id: arrival_airport_id) if arrival_airport_id.present?

    # flights that match departure
    @flights_dep = @flights.where(departure_airport_id: departure_airport_id) if departure_airport_id.present?

    # flights by departure time
    if start.present?
      start_datetime = Time.zone.parse(start)
      time_range = (start_datetime - 30.minutes)..(start_datetime + 30.minutes)
      @flights_time = @flights.where(start: time_range)
    end

    # Combined search query
    @flights_avail = @flights.where(arrival_airport_id: arrival_airport_id) if arrival_airport_id.present?
    if @flights_avail.nil?
      @flights_avail = @flights.where(departure_airport_id: departure_airport_id) if departure_airport_id.present?
    else
      @flights_avail = @flights_avail.where(departure_airport_id: departure_airport_id) if departure_airport_id.present?
    end
    if start.present?
      start_time = Time.zone.parse(start)
      time_range = (start_datetime - 30.minutes)..(start_datetime + 30.minutes)
      if @flights_avail.nil?
        @flights_avail = @flights.where(start: time_range)
      else
        @flights_avail = @flights_avail.where(start: time_range)
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>


<p> Number of passengers: <%= @number_of_passengers %> </p>
<p> Flight id: <%= @flight %> </p>


<%= form_with model: @booking do |form| %>
  <%= form.hidden_field :flight_id, value: params[:flight_id] %>
  <%= form.hidden_field :number_of_passengers, value: @number_of_passengers %>

  <% @booking.passengers.each_with_index do |passenger, index| %>
    <div>
      <h3>Passenger <%= index + 1 %></h3>
      <%= form.fields_for :passengers, passenger do |passenger_form| %>
        <%= passenger_form.label :name %>
        <%= passenger_form.text_field :name %>
        <br>
        <%= passenger_form.label :email %>
        <%= passenger_form.email_field :email %>
      <% end %>
    </div>
  <% end %>

  <%= form.submit "Reserve" %>
<% end %>

<%= link_to 'Search for more flights', flights_path %>

app/views/bookings/show.html.erb
<%= @booking %>

<h2>Booking #<%= @booking.id %></h2>

<div>
  <p>Passengers:</p>
  <% @booking.passengers.each do |passenger| %>
    <p>Name:</p>
    <%= passenger.name %>
    <p>Email:</p>
    <%= passenger.email %>
  <% end %>
</div>

app/views/flights/index.html.erb
<h1>Flights</h1>
<%= form_with url: flights_path, method: :get, local: true do |form| %>
  <p>Arrival Airport</p>
  <%= form.select :arrival_airport_id, @arrival_options, prompt: 'Select an airport' %>
  <p>Departure Airport</p>
  <%= form.select :departure_airport_id, @departure_options, prompt: 'Select an airport' %>
  <p>Departure Date and Time</p>
  <%= form.select :start,
    options_for_select(@formatted_flight_times.map { |formatted, time| [formatted, time.to_s] }),
    prompt: "Select a datetime",
    class: "form-control" %>

  <p>Number of Passengers</p>
  <%= form.select :passengers, [1, 2, 3, 4], prompt: 'Select the number of passengers'  %>

  <p>
  <%= form.submit "Search Flights", class: "btn btn-primary" %>
  </p>
<% end %>

<% unless @flights_avail.nil? %>
  <h2> Available Flights </h2>
  <%= form_with url: new_booking_path, method: :get, local: true do |f| %>
    <%= f.hidden_field :number_of_tickets, value: @number_of_tickets %>
    <ul>
    <% @flights_avail.each do |flight| %>
      <li>
        <%= f.radio_button :flight_id, flight.id %>
        <%= f.label :flight_id, "Flight ##{flight.flight_number} - #{flight.departure_airport.code} to #{flight.arrival_airport.code} at #{flight.start.strftime('%Y-%m-%d %H:%M')}" %>
      </li>
    <% end %>
    </ul>

    <%= f.submit "Book This Flight" %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= button_to "Sign in", new_user_session_path %>
<% end %>
<h1>ApplicationHomePage</h1>

<%= link_to 'Flights Page', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style='color = green' class='notice'><%= notice %>
    <p style='color = red' class='alert'><%= alert%>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>